[project]
name = "iic3533-2026-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AntonioVenegas", email = "antonio.venegas@uc.cl" }
]
requires-python = ">=3.13.15"
dependencies = [
    "joblib>=1.6.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "scikit-learn>=1.9.1",
    "threadpoolctl>=3.7.0",
]

[project.scripts]
iic3533-2026-2 = "iic3533_2026_2:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
